pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

name: $(SourceBranchName)-build$(Rev:.r)

steps:
# Build the .NET Core components
- script: |
    dotnet build --configuration $(buildConfiguration)

# Run project tests
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --no-restore'

# Publish output packages
- script:
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY --no-build --no-restore