pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

name: $(SourceBranchName)-build$(Rev:.r)

steps:
# Build the .NET Core components, run their tests and publish the output packages
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test ./test/BrokeredMessaging.Messaging.Tests --configuration $(buildConfiguration) --logger trx --no-build --no-restore
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY --no-build --no-restore

# Publish Test Results to Azure Pipelines/TFS
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TEST-*.xml'
    buildConfiguration: $(buildConfiguration)