pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
# Build the .NET Core components, run their tests and publish the output packages
- displayName: 'Build, test and publish packages'
  script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

# Publish Test Results to Azure Pipelines/TFS
- displayName: 'Publish test results'
  task: PublishTestResults@2
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TEST-*.xml'
    buildConfiguration: $(buildConfiguration)